spring.application.name=eduguide



#Core Database Connection
spring.datasource.url=jdbc:postgresql://ep-flat-lake-ax7qm4rb-pooler.c-4.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oditcxL30fKG
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Automatically build/update database tables from your Java Entities
spring.jpa.hibernate.ddl-auto=update

# Disable Flyway completely to stop the PostgreSQL 18 version crash
spring.flyway.enabled=false
